import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    machines: [
      "Leg Press",
      "Kabelmachine",
      "Smith Machine",
      "Lat Pulldown Machine",
      "Chest Press Machine",
      "Leg Extension Machine",
      "Leg Curl Machine",
      "Pec Deck (Butterfly)",
      "Seated Row Machine",
      "Shoulder Press Machine",
      "Hip Abductor/Adductor Machine",
      "Calf Raise Machine",
      "Hack Squat Machine",
      "Ab Crunch Machine",
      "Roeimachine",
      "Crosstrainer",
      "Loopband",
      "Hometrainer",
      "Assault Bike",
    ],
    accessories: [
      "Dumbbells",
      "Halterstang (Barbell)",
      "Kettlebell",
      "Weerstandsband",
      "Yoga Mat",
      "Foam Roller",
      "Ab Wheel",
      "Optrekstang",
      "TRX / Suspension Trainer",
      "Medicijnbal",
      "Fitnessbal (Swiss Ball)",
      "Springtouw",
      "Bosu Ball",
      "Gewichtsschijven",
      "EZ Curl Bar",
      "Parallettes",
      "Plyobox",
      "Battle Ropes",
      "Sliding Discs",
      "Enkelgewichten",
      "Dip Station",
    ],
  });
}
